// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: atoc.proto

package atoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Health_Check_FullMethodName = "/Health/Check"
)

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthClient interface {
	Check(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Health_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility.
type HealthServer interface {
	Check(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServer struct{}

func (UnimplementedHealthServer) Check(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}
func (UnimplementedHealthServer) testEmbeddedByValue()                {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	// If the following call panics, it indicates UnimplementedHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoc.proto",
}

const (
	ControllerSetup_GetIsSetup_FullMethodName = "/ControllerSetup/GetIsSetup"
	ControllerSetup_SetUp_FullMethodName      = "/ControllerSetup/SetUp"
)

// ControllerSetupClient is the client API for ControllerSetup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerSetupClient interface {
	GetIsSetup(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIsSetupResponse, error)
	SetUp(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type controllerSetupClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerSetupClient(cc grpc.ClientConnInterface) ControllerSetupClient {
	return &controllerSetupClient{cc}
}

func (c *controllerSetupClient) GetIsSetup(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetIsSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIsSetupResponse)
	err := c.cc.Invoke(ctx, ControllerSetup_GetIsSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerSetupClient) SetUp(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControllerSetup_SetUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerSetupServer is the server API for ControllerSetup service.
// All implementations must embed UnimplementedControllerSetupServer
// for forward compatibility.
type ControllerSetupServer interface {
	GetIsSetup(context.Context, *emptypb.Empty) (*GetIsSetupResponse, error)
	SetUp(context.Context, *SetupRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedControllerSetupServer()
}

// UnimplementedControllerSetupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerSetupServer struct{}

func (UnimplementedControllerSetupServer) GetIsSetup(context.Context, *emptypb.Empty) (*GetIsSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIsSetup not implemented")
}
func (UnimplementedControllerSetupServer) SetUp(context.Context, *SetupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUp not implemented")
}
func (UnimplementedControllerSetupServer) mustEmbedUnimplementedControllerSetupServer() {}
func (UnimplementedControllerSetupServer) testEmbeddedByValue()                         {}

// UnsafeControllerSetupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerSetupServer will
// result in compilation errors.
type UnsafeControllerSetupServer interface {
	mustEmbedUnimplementedControllerSetupServer()
}

func RegisterControllerSetupServer(s grpc.ServiceRegistrar, srv ControllerSetupServer) {
	// If the following call panics, it indicates UnimplementedControllerSetupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerSetup_ServiceDesc, srv)
}

func _ControllerSetup_GetIsSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerSetupServer).GetIsSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerSetup_GetIsSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerSetupServer).GetIsSetup(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerSetup_SetUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerSetupServer).SetUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerSetup_SetUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerSetupServer).SetUp(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerSetup_ServiceDesc is the grpc.ServiceDesc for ControllerSetup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerSetup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ControllerSetup",
	HandlerType: (*ControllerSetupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIsSetup",
			Handler:    _ControllerSetup_GetIsSetup_Handler,
		},
		{
			MethodName: "SetUp",
			Handler:    _ControllerSetup_SetUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoc.proto",
}
