// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: atoc.proto

package atoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_UNKNOWN     ServingStatus = 0
	ServingStatus_SERVING     ServingStatus = 1
	ServingStatus_NOT_SERVING ServingStatus = 2
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_atoc_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_atoc_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ServingStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ServingStatus(num)
	return nil
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_atoc_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ServingStatus         `protobuf:"varint,1,req,name=status,enum=ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_atoc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_atoc_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() ServingStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ServingStatus_UNKNOWN
}

type GetIsSetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSetup       *bool                  `protobuf:"varint,1,req,name=is_setup,json=isSetup" json:"is_setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsSetupResponse) Reset() {
	*x = GetIsSetupResponse{}
	mi := &file_atoc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsSetupResponse) ProtoMessage() {}

func (x *GetIsSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atoc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsSetupResponse.ProtoReflect.Descriptor instead.
func (*GetIsSetupResponse) Descriptor() ([]byte, []int) {
	return file_atoc_proto_rawDescGZIP(), []int{1}
}

func (x *GetIsSetupResponse) GetIsSetup() bool {
	if x != nil && x.IsSetup != nil {
		return *x.IsSetup
	}
	return false
}

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          *string                `protobuf:"bytes,1,req,name=port" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_atoc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atoc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_atoc_proto_rawDescGZIP(), []int{2}
}

func (x *SetupRequest) GetPort() string {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return ""
}

var File_atoc_proto protoreflect.FileDescriptor

const file_atoc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"atoc.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\x13HealthCheckResponse\x12&\n" +
	"\x06status\x18\x01 \x02(\x0e2\x0e.ServingStatusR\x06status\"/\n" +
	"\x12GetIsSetupResponse\x12\x19\n" +
	"\bis_setup\x18\x01 \x02(\bR\aisSetup\"\"\n" +
	"\fSetupRequest\x12\x12\n" +
	"\x04port\x18\x01 \x02(\tR\x04port*:\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022A\n" +
	"\x06Health\x127\n" +
	"\x05Check\x12\x16.google.protobuf.Empty\x1a\x14.HealthCheckResponse\"\x002\x80\x01\n" +
	"\x0fControllerSetup\x12;\n" +
	"\n" +
	"GetIsSetup\x12\x16.google.protobuf.Empty\x1a\x13.GetIsSetupResponse\"\x00\x120\n" +
	"\x05SetUp\x12\r.SetupRequest\x1a\x16.google.protobuf.Empty\"\x00B,Z*github.com/floffah/misecloud/api/atoc;atoc"

var (
	file_atoc_proto_rawDescOnce sync.Once
	file_atoc_proto_rawDescData []byte
)

func file_atoc_proto_rawDescGZIP() []byte {
	file_atoc_proto_rawDescOnce.Do(func() {
		file_atoc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoc_proto_rawDesc), len(file_atoc_proto_rawDesc)))
	})
	return file_atoc_proto_rawDescData
}

var file_atoc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atoc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atoc_proto_goTypes = []any{
	(ServingStatus)(0),          // 0: ServingStatus
	(*HealthCheckResponse)(nil), // 1: HealthCheckResponse
	(*GetIsSetupResponse)(nil),  // 2: GetIsSetupResponse
	(*SetupRequest)(nil),        // 3: SetupRequest
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_atoc_proto_depIdxs = []int32{
	0, // 0: HealthCheckResponse.status:type_name -> ServingStatus
	4, // 1: Health.Check:input_type -> google.protobuf.Empty
	4, // 2: ControllerSetup.GetIsSetup:input_type -> google.protobuf.Empty
	3, // 3: ControllerSetup.SetUp:input_type -> SetupRequest
	1, // 4: Health.Check:output_type -> HealthCheckResponse
	2, // 5: ControllerSetup.GetIsSetup:output_type -> GetIsSetupResponse
	4, // 6: ControllerSetup.SetUp:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_atoc_proto_init() }
func file_atoc_proto_init() {
	if File_atoc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoc_proto_rawDesc), len(file_atoc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_atoc_proto_goTypes,
		DependencyIndexes: file_atoc_proto_depIdxs,
		EnumInfos:         file_atoc_proto_enumTypes,
		MessageInfos:      file_atoc_proto_msgTypes,
	}.Build()
	File_atoc_proto = out.File
	file_atoc_proto_goTypes = nil
	file_atoc_proto_depIdxs = nil
}
